#! /bin/sh
bspc rule -r "*"

#### Autostart ####
sxhkd &
picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/aa.jpeg &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &
xrandr --output DP-2 --mode 1920x1080 --rate 144 --primary
xrandr --output HDMI-0 --mode 1920x1080 --right-of DP-2

#### Global configs ####
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# Monitor configs ####
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9
bspc wm -0 DP-2 HDMI-0

#### Window configs ####
bspc config border_width	0
bspc config window_gap		1
bspc config split_ratio		0.5

### Change pointer ###
xsetroot -cursor_name left_ptr &

### Keyboard layout ###
setxkbmap -option grp:alt_shift_toggle -model abnt2 -layout br,us &
