#! /bin/sh
bspc rule -r "*"

#### Autostart ####
sxhkd &
picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/Files/wallpapers/0000.jpg &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

# Monitor configs ####
bspc monitor DVI-I-1 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 1 2 3 4 5

#### Window configs ####
bspc config border_width	0
bspc config window_gap		1
bspc config split_ratio		0.5

#### Global configs ####
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
setxkbmap -option grp:alt_shift_toggle -model abnt2 -layout br,us &

#### Remove cross pointer ####
xsetroot -cursor_name left_ptr &
